Fixed strict mode error by getting rid of Octal literals.
Old Error:

/node_modules/less-middleware/lib/middleware.js:85
      console[type]('  \033[90m%s :\033[0m \033[36m%s\033[0m', key, val);
                                                      ^^
SyntaxError: Octal literals are not allowed in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> ()
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)